spring.application.name=library-vibe-system
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.url=jdbc:sqlite:library.db
spring.jpa.hibernate.ddl-auto=update
# This tells Spring Boot not to worry about standard Hibernate/JPA dialetcs
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration